### ISSUE TITLE
Point out availability of official AWX web and task containers

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/awx-container#22]
During and after AnsibleFest SF 2017, I started this project and wanted to quickly get a web and task container up on Docker Hub since there weren't officially-built/supported ones from Ansible.

However, there now exist official images which are also automated builds that sync up with AWX official releases:

  - https://hub.docker.com/r/ansible/awx_task/
  - https://hub.docker.com/r/ansible/awx_web/

At a minimum, this project should point out the existence of these official images in the README; but going further, while this project's goal is to be able to create the web and task containers fully custom following the more elaborate AWX install process, the included `docker-compose.yml` (highlighted in the README and in some highly-trafficed blog posts) is intended to give a simple and quick AWX environment for demo purposes.

It might be best to pin to the latest official images for the `docker-compose.yml`. Then I can either deprecate the `geerlingguy/` images, or figure out some way of making them maintainable via this project; see https://github.com/geerlingguy/awx-container/issues/1.

**Comment by philomatic** [comment]
Keep up your good work by using the official images.

I've just started using docker for more than just testing purposes and made the following observations:

- docker-compose is a great tool for demo **AND** production usage, indeed it's even intended by the docker docs.
- When using slightly more complicated software stacks (such as awx), always prefer a documented docker-compose.yml file instead of some docker-run instructions or even a script:

1. Download docker-compose.yml
2. Adapt ports, networking and some environment options
3. Run docker-compose up -d; start using.

So I was happy when Ansible decided to support docker as deployment platform for awx and disappointed by the way they're doing it, just looking at the prerequisites from https://github.com/ansible/awx/blob/devel/INSTALL.md:

- Ansible Requires Version 2.4+
- Docker
- docker-py Python module
- GNU Make
- Git

and using an ansible playbook to get even started. I mean I can understand that they're using their own technologies ofc, but it's not very docker like 😞 
It's more the opposite 😄 

A docker-compose.yml for a demo / small production setup however would ideally already ship with an Ansible Container itself, how about that?

Best regards

**Comment by geerlingguy** [comment]
Fixed via #27

**Comment by vijayscsa** [comment]
Hi,  Thanks for all support.  Can you please support how should I update /etc/resolv.conf in the AWX Task container ?   From AWX Container I can able to DNS Server, once I update in /etc/resolv.conf I am unable to resolve any hosts.   Please help me

Thanks,

vj

vijayscsa@gmail.com
