### ISSUE TITLE
Can not access the /api path (unable to login)

### ISSUE THREAD

**Issue by leifmadsen** [geerlingguy/awx-container#9]
I don't have a patch yet, but access to the `/api` path (which is required for logging in) is not available unless you use the hostname that is configured in the `/etc/tower/settings.py` file.

Fix here is probably to expose a default variable that can allow you to override the hostname. Work around for now is simply to add `awxweb` to your `/etc/hosts` file pointing at your servers IP address.

**Comment by geerlingguy** [comment]
> Fix here is probably to expose a default variable that can allow you to override the hostname.

Yeah, that's probably the best idea; would also make a few of the other odd behaviors I've seen go away (whenever a log message mentions `awxweb`...).

**Comment by leifmadsen** [comment]
So going through the AWX repo, I think the "fix" should land upstream in AWX project first. Then we would need to figure out how to allow the wrapper playbook (this one) to push configuration information host variable overrides (here) into the template (ney file) in the AWX installation.

Currently, this hostname appears to be hard coded, and needs to make things dynamic there. See:

https://github.com/ansible/awx/blob/bfea00f6dc6af0fb01057ce38e9d0337e6c589aa/installer/image_build/files/settings.py

**Comment by leifmadsen** [comment]
Also FYI

https://github.com/ansible/awx/blob/c5c926f29cfeaedb92c06ac067be1f4541380989/installer/local_docker/tasks/main.yml

**Comment by charltonkao** [comment]
I'm trying to access https://<tower_host>/api/v1 in order to add my awx instance as a "tower" provider in ManageIQ.  I keep getting redirected to http://<tower_host>:8052/api/v1/.  Adding awxweb to /etc/hosts didn't seem to help with this.  

Could it also be that 443 isn't exposed in the container?  
I CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                NAMES
e88091490fa3        ansible/awx_task:latest   "/tini -- /bin/sh -c "   2 days ago          Up 2 days           8052/tcp                             awx_task
57239f0211fe        ansible/awx_web:latest    "/tini -- /bin/sh -c "   2 days ago          Up 2 days           0.0.0.0:80->8052/tcp                 awx_web

**Comment by bradlyaolson** [comment]
I had the same issue. I'm newer to Linux, and one thing I had to do was adjust the selinux settings for the VM I was running the container on. Just a thought.

**Comment by geerlingguy** [comment]
I'm closing all issues on this repository as it has been deprecated; please see: https://github.com/geerlingguy/awx-container/issues/49
